src/NerdStore.WebApp.MVC/Controllers/EventosController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Core.Data.EventSourcing;

namespace NerdStore.WebApp.MVC.Controllers
{
    public class EventosController : Controller
    {
        private readonly IEventSourcingRepository _eventSourcingRepository;

        public EventosController(IEventSourcingRepository eventSourcingRepository)
        {
            _eventSourcingRepository = eventSourcingRepository;
        }

        [HttpGet("eventos/{id:guid}")]
        public async Task<IActionResult> Index(Guid id)
        {
            var eventos = await _eventSourcingRepository.ObterEventos(id);
            return View(eventos);
        }
    }
}

src/NerdStore.WebApp.MVC/Controllers/PedidoController.cs
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Core.Communication.Mediator;
using NerdStore.Core.Messages.CommonMessages.Notifications;
using NerdStore.Vendas.Application.Queries;

namespace NerdStore.WebApp.MVC.Controllers
{
    public class PedidoController : ControllerBase
    {
        private readonly IPedidoQueries _pedidoQueries;

        public PedidoController(IPedidoQueries pedidoQueries,
            INotificationHandler<DomainNotification> notifications,
            IMediatorHandler mediatorHandler) : base(notifications, mediatorHandler)
        {
            _pedidoQueries = pedidoQueries;
        }

        [Route("meus-pedidos")]
        public async Task<IActionResult> Index()
        {
            return View(await _pedidoQueries.ObterPedidosCliente(ClienteId));
        }
    }
}

src/NerdStore.WebApp.MVC/Views/Pedido/Index.cshtml
@model IEnumerable<NerdStore.Vendas.Application.Queries.ViewModels.PedidoViewModel>
@{
    ViewData["Title"] = "Index";
}

<div class="container">
    <div class="row">

        <div class="col-md-12">

            <h4>Meus Pedidos</h4>
            <hr>
            <h5>Confira o status do seu pedido</h5>

            @{
                if (Model.Any())
                {
                    <br><br>
                    <div class="table-responsive-sm">
                        <table class="table table-bordered">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">Pedido</th>
                                    <th scope="col">Data Pedido</th>
                                    <th scope="col">Status Pedido</th>
                                    <th scope="col">Valor</th>
                                    <th scope="col">Historia</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    foreach (var pedido in Model)
                                    {
                                        <tr>
                                            <td>@pedido.Codigo</td>
                                            <td>@pedido.DataCadastro.ToShortDateString()</td>
                                            <td>
                                                <h4>

                                                    @{
                                                        if (pedido.PedidoStatus == 4)
                                                        {
                                                            <span class="badge badge-success">
                                                                Pago
                                                            </span>
                                                        }
                                                        else if (pedido.PedidoStatus == 6)
                                                        {
                                                            <span class="badge badge-danger">
                                                                Cancelado
                                                            </span>
                                                        }
                                                    }

                                                </h4>
                                            </td>
                                            <td>@pedido.ValorTotal.ToString("C")</td>
                                            <td><a class="btn btn-info" asp-controller="Eventos" asp-action="Index" asp-route-id="@pedido.Id"><span class="far fa-clock"></span></a></td>
                                        </tr>
                                    }
                                }

                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <p>Nenhum pedido</p>
                }
            }

        </div>
    </div>
</div>