src/NerdStore.WebApp.MVC/Controllers/CarrinhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Catalogo.Application.Services;
using NerdStore.Core.Communication.Mediator;
using NerdStore.Core.Messages.CommonMessages.Notifications;
using NerdStore.Vendas.Application.Commands;
using NerdStore.Vendas.Application.Queries;
using NerdStore.Vendas.Application.Queries.ViewModels;

namespace NerdStore.WebApp.MVC.Controllers
{
    public class CarrinhoController : ControllerBase
    {
        private readonly IProdutoAppService _produtoAppService;
        private readonly IPedidoQueries _pedidoQueries;
        private readonly IMediatorHandler _mediatorHandler;

        public CarrinhoController(INotificationHandler<DomainNotification> notifications,
                                  IProdutoAppService produtoAppService, 
                                  IMediatorHandler mediatorHandler, 
                                  IPedidoQueries pedidoQueries) : base(notifications, mediatorHandler)
        {
            _produtoAppService = produtoAppService;
            _mediatorHandler = mediatorHandler;
            _pedidoQueries = pedidoQueries;
        }

        [Route("meu-carrinho")]
        public async Task<IActionResult> Index()
        {
            return View(await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }

        [HttpPost]
        [Route("meu-carrinho")]
        public async Task<IActionResult> AdicionarItem(Guid id, int quantidade)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            if (produto == null) return BadRequest();

            if (produto.QuantidadeEstoque < quantidade)
            {
                TempData["Erro"] = "Produto com estoque insuficiente";
                return RedirectToAction("ProdutoDetalhe", "Vitrine", new { id });
            }

            var command = new AdicionarItemPedidoCommand(ClienteId, produto.Id, produto.Nome, quantidade, produto.Valor);
            await _mediatorHandler.EnviarComando(command);

            if (OperacaoValida())
            {
                return RedirectToAction("Index");
            }

            TempData["Erros"] = ObterMensagensErro();
            return RedirectToAction("ProdutoDetalhe", "Vitrine", new { id });
        }

        [HttpPost]
        [Route("remover-item")]
        public async Task<IActionResult> RemoverItem(Guid id)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            if (produto == null) return BadRequest();

            var command = new RemoverItemPedidoCommand(ClienteId, id);
            await _mediatorHandler.EnviarComando(command);

            if (OperacaoValida())
            {
                return RedirectToAction("Index");
            }

            return View("Index", await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }

        [HttpPost]
        [Route("atualizar-item")]
        public async Task<IActionResult> AtualizarItem(Guid id, int quantidade)
        {
            var produto = await _produtoAppService.ObterPorId(id);
            if (produto == null) return BadRequest();

            var command = new AtualizarItemPedidoCommand(ClienteId, id, quantidade);
            await _mediatorHandler.EnviarComando(command);

            if (OperacaoValida())
            {
                return RedirectToAction("Index");
            }

            return View("Index", await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }

        [HttpPost]
        [Route("aplicar-voucher")]
        public async Task<IActionResult> AplicarVoucher(string voucherCodigo)
        {
            var command = new AplicarVoucherPedidoCommand(ClienteId, voucherCodigo);
            await _mediatorHandler.EnviarComando(command);

            if (OperacaoValida())
            {
                return RedirectToAction("Index");
            }

            return View("Index", await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }

        [Route("resumo-da-compra")]
        public async Task<IActionResult> ResumoDaCompra()
        {
            return View(await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }

        [HttpPost]
        [Route("iniciar-pedido")]
        public async Task<IActionResult> IniciarPedido(CarrinhoViewModel carrinhoViewModel)
        {
            var carrinho = await _pedidoQueries.ObterCarrinhoCliente(ClienteId);

            var command = new IniciarPedidoCommand(carrinho.PedidoId, ClienteId, carrinho.ValorTotal, carrinhoViewModel.Pagamento.NomeCartao,
                carrinhoViewModel.Pagamento.NumeroCartao, carrinhoViewModel.Pagamento.ExpiracaoCartao, carrinhoViewModel.Pagamento.CvvCartao);

            await _mediatorHandler.EnviarComando(command);

            if (OperacaoValida())
            {
                return RedirectToAction("Index", "Pedido");
            }

            return View("ResumoDaCompra", await _pedidoQueries.ObterCarrinhoCliente(ClienteId));
        }
    }
}

src/NerdStore.WebApp.MVC/Extensions/SummaryViewComponent.cs
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using NerdStore.Core.Messages.CommonMessages.Notifications;

namespace NerdStore.WebApp.MVC.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
        private readonly DomainNotificationHandler _notifications;

        public SummaryViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            _notifications = (DomainNotificationHandler)notifications;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var notificacoes = await Task.FromResult(_notifications.ObterNotificacoes());
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

src/NerdStore.WebApp.MVC/Views/Carrinho/Index.cshtml
@model NerdStore.Vendas.Application.Queries.ViewModels.CarrinhoViewModel
@{
    ViewData["Title"] = "Index";
}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">

            <vc:summary />

            @{
                if (Model?.Items != null)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Produto</th>
                                <th>Quantidade</th>
                                <th class="text-center">Valor</th>
                                <th class="text-center">Valor Total</th>
                                <th> </th>
                            </tr>
                        </thead>
                        <tbody>

                            @{
                                foreach (var item in Model.Items)
                                {
                                    <tr>
                                        <td class="col-sm-5 col-md-5">
                                            <div class="media">
                                                <div class="media-body">
                                                    <h4 class="media-heading"><a asp-controller="Vitrine" asp-action="ProdutoDetalhe" asp-route-id="@item.ProdutoId">@item.ProdutoNome</a></h4>
                                                </div>
                                            </div>
                                        </td>

                                        <td class="col-sm-2 col-md-2" style="text-align: center">
                                            <form method="post" asp-controller="Carrinho" asp-action="AtualizarItem">
                                                <input type="hidden" id="Id" name="Id" value="@item.ProdutoId" />
                                                <div class="row" style="float: left">
                                                    <input style="width: 70px" type="text" class="form-control" name="quantidade" id="quantidade" value="@item.Quantidade">
                                                </div>
                                                <div class="row" style="float: right">
                                                    <button type="submit" class="btn btn-success">
                                                        <span class="fas fa-sync"></span>
                                                    </button>
                                                </div>
                                            </form>
                                        </td>
                                        <td class="col-sm-1 col-md-1 text-center"><strong>@item.ValorUnitario.ToString("C")</strong></td>
                                        <td class="col-sm-1 col-md-1 text-center"><strong>@item.ValorTotal.ToString("C")</strong></td>

                                        <td class="col-sm-1 col-md-1">
                                            <form method="post" asp-controller="Carrinho" asp-action="RemoverItem">
                                                <input type="hidden" id="Id" name="Id" value="@item.ProdutoId" />
                                                <button type="submit" class="btn btn-danger">
                                                    <span class="fas fa-trash-alt"></span> Remover
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                }
                            }

                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td><h5>Subtotal</h5></td>
                                <td class="text-right"><h5><strong>@Model.SubTotal.ToString("C")</strong></h5></td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td colspan="2">
                                    <form method="post" asp-controller="Carrinho" asp-action="AplicarVoucher">
                                        <div class="row" style="float: left">
                                            <input placeholder="Voucher" style="width: 150px" type="text" class="form-control" name="VoucherCodigo" id="VoucherCodigo" value="@Model.VoucherCodigo">
                                        </div>
                                        <div class="row" style="float: right">
                                            <button type="submit" class="btn btn-success">
                                                <span class="fas fa-sync"></span>
                                            </button>
                                        </div>
                                    </form>
                                </td>
                                <td><h5>Desconto</h5></td>
                                <td class="text-right"><h5><strong>@Model.ValorDesconto.ToString("C")</strong></h5></td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td>
                                    <h3>Total</h3>
                                </td>
                                <td class="text-right">
                                    <h3><strong>@Model.ValorTotal.ToString("C")</strong></h3>
                                </td>
                            </tr>
                            <tr>
                                <td> </td>
                                <td> </td>
                                <td> </td>
                                <td>
                                    <a asp-controller="Vitrine" asp-action="Index" class="btn btn-dark">
                                        <span class="fa fa-shopping-cart"></span>Continuar Compra
                                    </a>
                                </td>
                                <td>
                                    <a asp-controller="Carrinho" asp-action="ResumoDaCompra" class="btn btn-success">
                                        <span class="fas fa-play"></span><br /> Finalizar Compra
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                }
                else
                {
                    <div><p>Carrinho Vazio</p></div>
                }
            }
        </div>
    </div>
</div>

src/NerdStore.WebApp.MVC/Views/Carrinho/ResumoDaCompra.cshtml
@model NerdStore.Vendas.Application.Queries.ViewModels.CarrinhoViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="container">

    <vc:summary />

    <div class="row">

        @{
            if (Model.Items.Any())
            {
                <div class="col-md-4 order-md-2 mb-4">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Resumo da Compra</span>
                        <span class="badge badge-secondary badge-pill">@Model.Items.Count</span>
                    </h4>
                    <ul class="list-group mb-3">

                        @{
                            foreach (var item in Model.Items)
                            {
                                <li class="list-group-item d-flex justify-content-between lh-condensed">
                                    <div>
                                        <h6 class="my-0">@item.ProdutoNome</h6>
                                        <small class="text-muted">@item.Quantidade Unidades</small>
                                    </div>
                                    <span class="text-muted">@item.ValorTotal.ToString("C")</span>
                                </li>
                            }

                            if (!string.IsNullOrEmpty(Model.VoucherCodigo))
                            {
                                <li class="list-group-item d-flex justify-content-between bg-light">
                                    <div class="text-success">
                                        <h6 class="my-0">Voucher Utilizado</h6>
                                        <small>@Model.VoucherCodigo</small>
                                    </div>
                                    <span class="text-success">-@Model.ValorDesconto.ToString("C")</span>
                                </li>
                            }

                            <li class="list-group-item d-flex justify-content-between">
                                <span>Total</span>
                                <strong>@Model.ValorTotal.ToString("C")</strong>
                            </li>
                        }
                    </ul>

                </div>
                <div class="col-md-8 order-md-1">
                    <form method="post" asp-controller="Carrinho" asp-action="IniciarPedido">

                        <h4 class="mb-3">Pagamento</h4>
                        <hr class="mb-4">
                        <div class="row">
                            <img class="img-fluid" src="Images/cards.png">

                        </div>
                        <br /><br />
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label>Nome no Cartão</label>
                                <input asp-for="Pagamento.NomeCartao" type="text" class="form-control" placeholder="" required="">
                                <small class="text-muted">Nome completo como consta no cartão</small>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label>Número do Cartão</label>
                                <input asp-for="Pagamento.NumeroCartao" type="text" class="form-control" placeholder="" required="">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3 mb-3">
                                <label>Data Expiração</label>
                                <input asp-for="Pagamento.ExpiracaoCartao" type="text" class="form-control" placeholder="" required="">
                            </div>
                            <div class="col-md-3 mb-3">
                                <label>CVV</label>
                                <input asp-for="Pagamento.CvvCartao" type="text" class="form-control" placeholder="" required="">
                            </div>
                        </div>
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Finalizar Compra</button>
                    </form>
                </div>
            }
            else
            {
                <div><p>Carrinho Vazio</p></div>
            }
        }

    </div>
</div>